### ISSUE TITLE
Fix CSS for prod builds. 

### ISSUE THREAD

**Issue by rwjblue** [glimmerjs/todomvc-demo#19]
See https://github.com/glimmerjs/glimmer-application-pipeline/issues/74#issuecomment-292790467.

Basic gist:

```js
class CustomApp extends GlimmerApp {
 cssTree() {
   let cssTree = super();
   return customBroccoliStuff(cssTree);
 }
}
let app = new CustomApp(defaults);
return app.toTree();
```

**Comment by cafreeman** [comment]
@rwjblue I've got this working on my other app now, so I'll fix it here as well. Expect a PR soon. :)

**Comment by mmun** [comment]
Should this be closed?
